defaults:
  -
    scope:
      path: ''
    values:
      layout: default
permalink: /:year/:month/:day/:title
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
  gfm_quirks: [paragraph_end, no_auto_typographic]
plugins:
  # Enable all GitHub Pages plugins so local dev is exactly like live.
  - jekyll-github-metadata
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
exclude:
  - Gemfile*
  - bower.json
  - Makefile
  - lib/bundle
  - node_modules
  - package*.json
  - jsconfig.json
  - rougify.rb
  - '*.ts'
